# Site settings
title: "Nischay Singh"
email: bajwa.nischay@gmail.com
description: "Blog"
baseurl: ""
url: "http://bajwanischay.github.io/"
title_description: "Finance | Tech | Business | Military | Politics"
title_image: "/Chicago.jpg"
google_analytics: "UA-89774547-1"
github_repository: https://github.com/bajwanischay/bajwanischay.github.io
post_limit: 5

# Social usernames/URLs
instagram_username: bajwa.nischay
linkedin_link: https://www.linkedin.com/in/nischay-singh
soundcloud_profile: bajwanischay

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
