# Site settings
title: "Nischay Singh"
email: bajwa.nischay@gmail.com
description: "Blog"
baseurl: ""
url: "http://bajwanischay.github.io/"
title_description: "Finance | Tech | Business | Military | Politics"
title_image: "/8.JPG"
google_analytics: "UA-89774547-1"
disqus_account: nischay_singh
github_repository: https://github.com/bajwanischay/bajwanischay.github.io
post_limit: 5

# Social usernames/URLs
github_username:  bajwanischay
instagram_username: flashboybajwa
linkedin_link: nischay-singh
soundcloud_profile: bajwanischay
quora_profile: Nischay-Singh


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
